---
- name: install dependency packages
  apt:
    name:
      - python-certifi
      - python-requests
      - python-future
- name: intsall boto3
  apt:
    name: python-boto3
  when: lexicon_install_boto3
- name: install lexicon
  pip:
    name: dns-lexicon
