---
- name: install dependency packages
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - python-requests
    - python2-boto3
    - python2-future
    - python-idna
- name: install lexicon
  pip:
    name: dns-lexicon
    state: latest
